apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  clusterIP: 10.254.10.10
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    name: nginx
