apiVersion: v1
kind: Service
metadata:
  name: owncloud
  labels:
    name: owncloud
spec:
  clusterIP: 10.254.10.30
  ports:
    - name: php-fpm
      port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    name: owncloud
