apiVersion: v1
kind: ReplicationController
metadata:
  name: postgresql
  labels:
    name: postgresql 
spec:
  replicas: 1
  selector:
    name: postgresql
  template:
    metadata:
      labels:
        name: postgresql
    spec:
      containers:
        - name: postgresql
          image: sameersbn/postgresql:9.4-17
          env:
            - name: DB_USER
              value: owncloud
            - name: DB_PASS
              value: password
            - name: DB_NAME
              value: owncloud_db
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/postgresql
              name: postgresql-data
          livenessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 30
            timeoutSeconds: 5
      volumes:
        - name: postgresql-data
          hostPath:
            # the directory on Host Node for saving data
            path: /mnt/data/db
