apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    name: postgresql
spec:
  clusterIP: 10.254.10.20
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    name: postgresql
